[package]
name = "bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
elements = { workspace = true }
thiserror = "1.0.50"
serde_json =  { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
tokio = { workspace = true }
boltz-client = { path = "..", features = ["ws", "esplora", "electrum"] }
uniffi = { version = "0.29.2", features = ["cli", "tokio"] }

[build-dependencies]
uniffi = { version = "0.29.2", features = ["build"] }

[dev-dependencies]
uniffi = { version = "0.29.2", features = ["bindgen-tests"] }
serial_test = { workspace = true }

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "boltz_client"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
