on:
  push:
    branches:
      - master
  pull_request:

name: lint

jobs:
  fmt:
    name: rust fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set default toolchain
        run: rustup default nightly
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Set profile
        run: rustup set profile minimal
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Add clippy
        run: rustup component add clippy
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Update toolchain
        run: rustup update
      - name: Check fmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: make cargo-clippy
      - name: Clippy wasm
        run: make wasm-clippy
      - name: Check python
        working-directory: bindings
        run: make check-python
